### ISSUE TITLE
Cannot download files (EMC portal) when file names have a space. 

### ISSUE THREAD

**Issue by eroma2014** [apache/airavata-data-lake#82]
Files are available to download from EMC portal, which uses Data-lake is with spaces in the name.
When tried to download, it shows 'Failed-no file'

File name spaces should be disregarded and should be able to download.

**Comment by DImuthuUpe** [comment]
Fixed in https://github.com/apache/airavata-mft/commit/479b292a9bcd73bb76e6991bfa69ba09738cdc45
